# Generated by Django 3.0.6 on 2020-05-11 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noshdapp', '0002_user_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
